# This will automatically apply every terraform change in the ami and launch_template. Be sure that
# every change is related to the new image generated by packer. Be careful.
deploy_gpterror:
	cd packer 	 && packer build gpterror/image.pkr.hcl
	cd terraform && terraform apply --auto-approve --target aws_ami.gpterror --target aws_launch_template.this

deploy_cert_renewer:
	cd packer 	 && packer build cert_renewer/image.pkr.hcl
	cd terraform && terraform apply --auto-approve --target aws_ami.cert_renewer --target aws_launch_template.cert_renewer
