# This will automatically apply every terraform change in the ami and launch_template. Be sure that
# every change is related to the new image generated by packer. Be careful.
deploy_image:
	cd packer 	 && packer build image.pkr.hcl
	cd terraform && terraform apply --auto-approve --target aws_ami.gpterror --target aws_launch_template.this
